SELECT HOTEN AS HOTEN_GV,LUONG AS LUONG_GV
FROM GIAOVIEN
WHERE LUONG >2000;

SELECT *
FROM GIAOVIEN
WHERE NGAYSINH BETWEEN'1960/1/1'AND'1975/12/31';


SELECT*
FROM GIAOVIEN 
WHERE GVQLCM IS NOT NULL;


SELECT*
FROM GIAOVIEN
WHERE LUONG IN(2000,3000,4000);

SELECT*
FROM GIAOVIEN
WHERE DIACHI LIKE '%TP HCM';

SELECT TENDT,CAPQL
FROM DETAI
WHERE DATEDIFF(NGAYBD,'2005-04-30')>0;


SELECT HOTEN,YEAR(NOW())-YEAR(NGAYSINH) AS AGE
FROM GIAOVIEN;


SELECT *
FROM GIAOVIEN
WHERE year(NGAYSINH) >= 1975;

SELECT LUONG AS LUONG_TRUOC ,LUONG*1.1 AS LUONG_SAU
FROM GIAOVIEN;

SELECT HOTEN,TENBM
FROM GIAOVIEN,BOMON
WHERE GIAOVIEN.MABM=BOMON.MABM;

SELECT HOTEN,TENBM
FROM GIAOVIEN,BOMON
WHERE BOMON.TRUONGBM=GIAOVIEN.MAGV;


SELECT GV.HOTEN, KH.TENKHOA
FROM KHOA AS KH,GIAOVIEN AS GV
WHERE KH.TRUONGKHOA=GV.MAGV;

SELECT GV.HOTEN, NT.TEN AS NGUOITHAN_GV
FROM GIAOVIEN GV,NGUOITHAN NT
WHERE GV.MAGV=NT.MAGV;

SELECT GV.HOTEN , QL.HOTEN AS NGUOI_QUAN_LY
FROM GIAOVIEN GV, GIAOVIEN QL
WHERE GV.GVQLCM=QL.MAGV;


SELECT GV.HOTEN, KH.TENKHOA
FROM GIAOVIEN GV, KHOA KH ,BOMON BM
WHERE GV.MABM=BM.MABM AND BM.MAKHOA=KH.MAKHOA;

SELECT GV.HOTEN, BM.TENBM
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM=BM.MABM;


USE HOCSINHDB;
#Q1. Cho biết họ tên và mức lương của các giáo viên nữ.
SELECT GV.HOTEN, GV.LUONG
FROM GIAOVIEN GV
 WHERE PHAI LIKE'Nữ';
 
 
 #Q2. Cho biết họ tên của các giáo viên và lương của họ sau khi tăng 10%.
SELECT GV.HOTEN ,GV.LUONG ,GV.LUONG*1.1 AS LUONG_TANG
FROM GIAOVIEN GV;


#Q3. Cho biết mã của các giáo viên có họ tên bắt đầu là “Nguyễn” 
#và lương trên $2000 hoặc, giáo viên là trưởng bộ môn nhận chức sau năm 1995.
SELECT GV.MAGV AS MASO, GV.HOTEN AS HO_TEN
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM=BM.MABM
WHERE ((GV.HOTEN LIKE 'Nguyễn%' AND GV.LUONG>=2000) OR (BM.TRUONGBM=GV.MAGV AND YEAR(BM.NGAYNHANCHUC)>=1995));

#Q4. Cho biết tên những giáo viên khoa Công nghệ thông tin.
SELECT GV.HOTEN
FROM BOMON BM
JOIN GIAOVIEN GV ON GV.MABM=BM.MABM 
JOIN KHOA KH ON KH.MAKHOA=BM.MAKHOA
WHERE KH.TENKHOA LIKE'Công nghệ thông tin';

#Q5. Cho biết tên của bộ môn cùng họ tên giảng viên làm trưởng bộ môn đó.
SELECT GV.*, BM.TENBM
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MAGV=BM.TRUONGBM;

#Q6. Với mỗi giáo viên, hãy cho biết thông tin của bộ môn mà họ đang làm việc.
SELECT GV.HOTEN, BM.*
FROM GIAOViEN GV JOIN BOMON BM ON GV.MABM=BM.MABM;

#Q7. Cho biết tên đề tài và giáo viên chủ nhiệm đề tài.
SELECT DT.MADT,DT.TENDT,GV.HOTEN
FROM DETAI DT 
JOIN GIAOVIEN GV ON DT.GVCNDT=GV.MAGV;

#Q8. Với mỗi khoa cho biết thông tin trưởng khoa
SELECT KH.*,GV.HOTEN
FROM KHOA KH
JOIN GIAOVIEN GV ON GV.MAGV=KH.TRUONGKHOA;


#Q9. Cho biết các giáo viên của bộ môn “Vi sinh” có tham gia đề tài 006.
SELECT DISTINCT GV.HOTEN
FROM THAMGIADT TGDT
JOIN GIAOVIEN GV ON TGDT.MAGV=GV.MAGV
JOIN BOMON BM ON GV.MABM=BM.MABM
WHERE BM.TENBM='Vi sinh' AND TGDT.MADT='006';

USE HOCSINHDB;
#Q10. Với những đề tài thuộc cấp quản lý “ĐHQG”, cho biết mã đề tài, đề tài thuộc về chủ đề nào,
#họ tên người chủ nghiệm đề tài 


SELECT DT.MADT,DT.TENDT,DT.CAPQL,CD.MACD,CD.TENCD,GV.HOTEN
FROM DETAI DT 
JOIN CHUDE CD ON DT.MACD=CD.MACD 
JOIN GIAOVIEN GV ON GV.MAGV=DT.GVCNDT
WHERE DT.CAPQL='ĐHQG' ;


#Q11. Tìm họ tên của từng giáo viên và người phụ trách chuyên môn trực tiếp của giáo viên đó.
SELECT GV.HOTEN, QL.HOTEN AS HO_TEN_GV_QUAN_LY
FROM GIAOVIEN GV 
JOIN GIAOVIEN QL ON GV.GVQLCM=QL.MAGV;

#Q12. Tìm họ tên của những giáo viên được “Nguyễn An Trung” phụ trách trực tiếp.
SELECT GV.HOTEN
FROM GIAOVIEN GV
JOIN GIAOVIEN QL ON GV.GVQLCM=QL.MAGV
WHERE QL.HOTEN ='Nguyễn An Trung';

#Q13. Cho biết tên giáo viên là trưởng bộ môn “Hệ thống thông tin”

SELECT GV.*
FROM GIAOVIEN GV
JOIN BOMON BM ON GV.MAGV=BM.TRUONGBM
WHERE BM.TENBM='Hệ thống thông tin';

#Q14. Cho biết tên người chủ nhiệm đề tài của những đề tài thuộc chủ đề Quản lý giáo dục.
SELECT DISTINCT GV.HOTEN
FROM GIAOVIEN GV
JOIN DETAI DT ON GV.MAGV=DT.GVCNDT 
JOIN CHUDE CD ON CD.MACD=DT.MACD
WHERE CD.TENCD='Quản lý giáo dục';

#Q15. Cho biết tên các công việc của đề tài 'HTTT quản lý các trường ĐH' 
#có thời gian bắt đầu trong tháng 3/2008.
SELECT CV.TENCV
FROM CONGVIEC CV
JOIN DETAI DT ON CV.MADT=DT.MADT
WHERE DT.TENDT='HTTT quản lý các trường ĐH' AND CV.NGAYBD >='2008-03-01';
#Q16. Cho biết tên giáo viên và tên người quản lý chuyên môn của giáo viên đó.
SELECT GV.HOTEN, QL.HOTEN AS HO_TEN_QUAN_LY
FROM GIAOVIEN GV
JOIN GIAOVIEN QL ON GV.GVQLCM=QL.MAGV;

#Q17. Cho các công việc bắt đầu trong khoảng từ 01/01/2007 đến 01/08/2007.
SELECT CV.TENCV
FROM CONGVIEC CV
WHERE CV.NGAYBD >='2007-01-01' AND CV.NGAYBD<='2007-08-01';
#
SELECT CV.TENCV
FROM CONGVIEC CV
WHERE CV.NGAYBD between '2007-01-01' AND '2007-08-01';
#Q18. Cho biết họ tên các giáo viên cùng bộ môn với giáo viên “Trần Trà Hương”.
SELECT GV1.HOTEN
FROM GIAOVIEN GV1
WHERE GV1.MABM= (SELECT GV.MABM 
FROM GIAOVIEN GV
WHERE GV.HOTEN='Trần Trà Hương') AND GV1.HOTEN!='Trần Trà Hương'; 

#Q19. Tìm những giáo viên vừa là trưởng bộ môn, vừa chủ nhiệm đề tài.
SELECT GV.*
FROM GIAOVIEN GV
JOIN DETAI DT ON GV.MAGV=DT.GVCNDT
JOIN BOMON BM ON GV.MAGV=BM.TRUONGBM;

#Q20. Cho biết tên những giáo viên vừa là trưởng khoa và vừa là trưởng bộ môn
SELECT GV.*
FROM GIAOVIEN GV
JOIN KHOA KH ON KH.TRUONGKHOA=GV.MAGV
JOIN BOMON BM ON BM.TRUONGBM=GV.MAGV;

#Q21. Cho biết tên những trưởng bộ môn mà vừa chủ nhiệm đề tài.
SELECT DISTINCT GV.HOTEN 
FROM GIAOVIEN GV
JOIN BOMON BM ON GV.MAGV=BM.TRUONGBM
JOIN DETAI DT ON GV.MAGV=DT.GVCNDT;
#Q22. Cho biết mã số các trưởng khoa có chủ nhiệm đề tài.
SELECT GV.MAGV,GV.HOTEN,KH.TENKHOA,DT.TENDT AS TEN_DE_TAI_CN
FROM GIAOVIEN GV
JOIN KHOA KH ON GV.MAGV=KH.TRUONGKHOA
JOIN DETAI DT ON GV.MAGV=DT.GVCNDT;


#Q23. Cho biết mã số các giáo viên thuộc bộ môn “HTTT” hoặc có tham gia đề tài mã “001”
SELECT  GV.MAGV,GV.HOTEN,TGDT.MADT
FROM GIAOVIEN GV
JOIN THAMGIADT TGDT ON GV.MAGV=TGDT.MAGV
WHERE TGDT.MADT='001';

#Q24. Cho biết giáo viên làm việc cùng bộ môn với giáo viên 002.
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE GV.MABM=(
	SELECT GV1.MABM
    FROM GIAOVIEN GV1
    WHERE GV1.MAGV=002
) AND GV.MAGV!=002;

#Q25. Tìm những giáo viên là trưởng bộ môn.
SELECT GV.HOTEN
FROM GIAOVIEN GV
JOIN BOMON BM ON GV.MAGV=BM.TRUONGBM;

#Q26. Cho biết họ tên và mức lương của các giáo viên
SELECT GV.HOTEN, GV.LUONG
FROM GIAOVIEN GV